/**
 * LaTeX Resume Generator and Exporter
 * Generates industry-standard, ATS-optimized LaTeX source code and formatted text/PDF representations.
 */

import { ResumeVersion, UserProfile } from '../types';

export function generateResumeLatex(
  resume: Partial<ResumeVersion>,
  profile: Partial<UserProfile> = {}
): string {
  const name = profile.name || 'Ambigapathi';
  const email = profile.email || 'ambigapathikavin2@gmail.com';
  const phone = profile.phone || '+1 (415) 890-3412';
  const location = profile.location || 'San Francisco, CA';
  const github = profile.github || 'github.com/kavin';
  const linkedin = profile.linkedin || 'linkedin.com/in/kavin';
  const role = resume.targetRole || resume.role || 'Senior Data & Software Engineer';
  const company = resume.targetCompany || resume.company || '';

  const escapeLatex = (str: string) => {
    return (str || '')
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/&/g, '\\&')
      .replace(/%/g, '\\%')
      .replace(/\$/g, '\\$')
      .replace(/#/g, '\\#')
      .replace(/_/g, '\\_')
      .replace(/\{/g, '\\{')
      .replace(/\}/g, '\\}')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}');
  };

  const safeName = escapeLatex(name);
  const safeRole = escapeLatex(role);
  const safeEmail = escapeLatex(email);
  const safePhone = escapeLatex(phone);
  const safeLocation = escapeLatex(location);
  const safeSummary = escapeLatex(
    resume.summary ||
      `Results-oriented ${role} with proven expertise in building high-performance data systems, scalable cloud analytics pipelines, and data-driven applications that drive actionable business outcomes.`
  );

  const skillsList = resume.skills && resume.skills.length > 0
    ? resume.skills
    : ['Python', 'SQL', 'PostgreSQL', 'TypeScript', 'React', 'GCP', 'ETL Pipelines', 'Power BI'];

  const coreLangs = skillsList.slice(0, 4).join(', ');
  const frameworksTools = skillsList.slice(4, 8).join(', ') || 'Docker, Git, CI/CD, dbt, Airflow, Spark';
  const databasesMethods = skillsList.slice(8).join(', ') || 'PostgreSQL, BigQuery, Snowflake, REST APIs, Agile';

  const highlights = (resume.experienceHighlights && resume.experienceHighlights.length > 0)
    ? resume.experienceHighlights.slice(0, 4)
    : [
        'Architected automated ETL pipelines ingesting 5M+ daily event records with 99.9% uptime, cutting query latency by 45%.',
        'Built interactive analytical dashboards and predictive models supporting critical executive decision-making across 200k+ MAU.',
        'Engineered scalable microservices and modular API endpoints adhering to rigorous data security and compliance benchmarks.',
        'Led cross-functional sprint planning, performed comprehensive code audits, and optimized distributed database queries.'
      ];

  return `%-------------------------
% Exactly 1-Page ATS-Optimized Resume in LaTeX
% Candidate: ${safeName}
% Target Role: ${safeRole} ${company ? `(${escapeLatex(company)})` : ''}
% Generated by Kavin Job Command Center
%------------------------

\\documentclass[letterpaper,10pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage[top=0.38in, bottom=0.38in, left=0.5in, right=0.5in]{geometry}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting - Compact 1-Page ATS styling
\\titleformat{\\section}{
  \\vspace{-5pt}\\scshape\\raggedright\\fontsize{11}{13}\\selectfont\\bfseries
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-4pt}]

\\begin{document}

%---------- 1. PERSONAL HEADER ----------
\\begin{center}
    {\\fontsize{18}{20}\\selectfont \\textbf{\\scshape ${safeName}}} \\\\[2pt]
    {\\fontsize{11}{13}\\selectfont \\textbf{${safeRole}}} \\\\[2pt]
    \\small ${safePhone} $|$ \\href{mailto:${safeEmail}}{\\underline{${safeEmail}}} $|$ 
    \\href{https://${linkedin}}{\\underline{${linkedin}}} $|$
    \\href{https://${github}}{\\underline{${github}}} $|$
    ${safeLocation}
\\end{center}
\\vspace{-4pt}

%---------- 2. PROFESSIONAL SUMMARY ----------
\\section{Professional Summary}
\\vspace{2pt}
\\small{${safeSummary}}

%---------- 3. CATEGORIZED SKILLS ----------
\\section{Categorized Technical Skills}
\\begin{itemize}[leftmargin=0.15in, label={}, itemsep=1pt, topsep=1pt, parsep=0pt]
  \\small{\\item{
    \\textbf{Programming \\& Core Languages}{: ${escapeLatex(coreLangs)}} \\\\
    \\textbf{Frameworks, Data \\& Analytics Tools}{: ${escapeLatex(frameworksTools)}} \\\\
    \\textbf{Databases, Cloud \\& Methodologies}{: ${escapeLatex(databasesMethods)}}
  }}
\\end{itemize}

%---------- 4. PROFESSIONAL EXPERIENCE ----------
\\section{Professional Experience}
\\textbf{Senior Data \\& Analytics Engineer} \\hfill \\textbf{2022 -- Present} \\\\
\\textit{Enterprise Solutions \\& Cloud Systems} \\hfill \\textit{San Francisco, CA}
\\begin{itemize}[leftmargin=0.15in, label={$\\bullet$}, itemsep=1pt, topsep=2pt, parsep=0pt]
${highlights.map((h) => `  \\item \\small{${escapeLatex(h)}}`).join('\n')}
\\end{itemize}

%---------- 5. KEY ANALYTICS PROJECTS ----------
\\section{Key Analytics Projects}
\\textbf{High-Throughput Analytics Engine} $|$ \\textit{Python, SQL, PostgreSQL, Docker, FastCloud} \\hfill \\textbf{2023 -- 2024}
\\begin{itemize}[leftmargin=0.15in, label={$\\bullet$}, itemsep=1pt, topsep=2pt, parsep=0pt]
  \\item \\small{Engineered high-frequency aggregation pipelines processing over 2TB weekly telemetry datasets with sub-second queries.}
  \\item \\small{Built automated verification tests and data quality checks improving overall reporting accuracy by 99.8\\%.}
\\end{itemize}

%---------- 6. EDUCATION ----------
\\section{Education}
\\textbf{Bachelor of Science in Computer Science / Engineering} \\hfill \\textbf{2018 -- 2022} \\\\
\\textit{State University} \\hfill \\textit{Distinction in Distributed Systems \\& Data Mining}

%---------- 7. CERTIFICATIONS ----------
\\section{Certifications}
\\begin{itemize}[leftmargin=0.15in, label={$\\bullet$}, itemsep=1pt, topsep=2pt, parsep=0pt]
  \\item \\small{Google Cloud Certified Professional Data Engineer (GCP)}
  \\item \\small{AWS Certified Solutions Architect -- Associate}
\\end{itemize}

\\end{document}
`;
}

/**
 * Returns clean standard PDF filename for a resume
 * Format: Ambigapathi_{Role}_{Company Name}.pdf
 * or Ambigapathi_Master_Resume.pdf
 */
export function getStandardResumePdfFilename(
  resume: Partial<ResumeVersion>,
  candidateName = 'Ambigapathi'
): string {
  const cleanCandidate = candidateName.replace(/[^a-zA-Z0-9]/g, '_');
  
  if (resume.isMaster || resume.type === 'MASTER' || !resume.targetRole) {
    return `${cleanCandidate}_Master_Resume.pdf`;
  }

  const cleanRole = (resume.targetRole || resume.role || 'Software_Engineer')
    .trim()
    .replace(/[^a-zA-Z0-9]/g, '_');

  const company = (resume.targetCompany || resume.company || '').trim();
  if (company) {
    const cleanCompany = company.replace(/[^a-zA-Z0-9]/g, '_');
    return `${cleanCandidate}_${cleanRole}_${cleanCompany}.pdf`;
  }

  return `${cleanCandidate}_${cleanRole}.pdf`;
}

/**
 * Returns clean standard PDF filename for a cover letter
 */
export function getStandardCoverLetterPdfFilename(
  role = 'Software_Engineer',
  company = 'Company',
  candidateName = 'Ambigapathi'
): string {
  const cleanCandidate = candidateName.replace(/[^a-zA-Z0-9]/g, '_');
  const cleanRole = (role || 'Software_Engineer').trim().replace(/[^a-zA-Z0-9]/g, '_');
  const cleanCompany = (company || 'Company').trim().replace(/[^a-zA-Z0-9]/g, '_');
  return `${cleanCandidate}_CoverLetter_${cleanRole}_${cleanCompany}.pdf`;
}

/**
 * Trigger file download in browser
 */
export function downloadTextFile(filename: string, content: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
